--------------------------------------------------------
--  File created - Friday-October-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROMOTION_DETAIL
--------------------------------------------------------

  CREATE TABLE "BIBIM"."PROMOTION_DETAIL" 
   (	"PROMD_ID" VARCHAR2(10 BYTE), 
	"DATE_SRT" DATE, 
	"PRODUCT_ID" VARCHAR2(20 BYTE), 
	"PROM_ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BIBIM.PROMOTION_DETAIL
SET DEFINE OFF;
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod01',to_date('04-OCT-17','DD-MON-RR'),'P_01','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod02',to_date('03-AUG-14','DD-MON-RR'),'P_06','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod03',to_date('02-JAN-14','DD-MON-RR'),'P_38','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod04',to_date('25-MAR-16','DD-MON-RR'),'P_32','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod05',to_date('18-MAR-14','DD-MON-RR'),'P_46','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod06',to_date('28-AUG-15','DD-MON-RR'),'P_11','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod07',to_date('11-JUN-16','DD-MON-RR'),'P_149','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod08',to_date('16-JUL-15','DD-MON-RR'),'P_72','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod09',to_date('24-JUL-15','DD-MON-RR'),'P_116','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod10',to_date('07-JUN-15','DD-MON-RR'),'P_40','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod11',to_date('02-FEB-15','DD-MON-RR'),'P_161','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod12',to_date('22-NOV-16','DD-MON-RR'),'P_82','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod13',to_date('21-JAN-13','DD-MON-RR'),'P_17','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod14',to_date('04-NOV-13','DD-MON-RR'),'P_104','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod15',to_date('01-APR-15','DD-MON-RR'),'P_80','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod16',to_date('20-JUN-15','DD-MON-RR'),'P_157','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod17',to_date('11-SEP-13','DD-MON-RR'),'P_53','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod18',to_date('12-FEB-16','DD-MON-RR'),'P_35','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod19',to_date('26-APR-13','DD-MON-RR'),'P_138','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod20',to_date('25-MAR-14','DD-MON-RR'),'P_10','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod21',to_date('13-NOV-14','DD-MON-RR'),'P_17','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod22',to_date('08-JAN-15','DD-MON-RR'),'P_100','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod23',to_date('02-OCT-16','DD-MON-RR'),'P_65','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod24',to_date('05-OCT-13','DD-MON-RR'),'P_166','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod25',to_date('14-OCT-16','DD-MON-RR'),'P_68','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod26',to_date('02-APR-13','DD-MON-RR'),'P_51','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod27',to_date('15-JUL-13','DD-MON-RR'),'P_21','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod28',to_date('19-SEP-13','DD-MON-RR'),'P_46','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod29',to_date('23-MAR-14','DD-MON-RR'),'P_138','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod30',to_date('02-AUG-15','DD-MON-RR'),'P_155','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod31',to_date('28-MAR-16','DD-MON-RR'),'P_104','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod32',to_date('02-MAR-16','DD-MON-RR'),'P_28','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod33',to_date('18-SEP-16','DD-MON-RR'),'P_19','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod34',to_date('24-NOV-14','DD-MON-RR'),'P_55','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod35',to_date('03-JUL-15','DD-MON-RR'),'P_77','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod36',to_date('20-JUN-14','DD-MON-RR'),'P_03','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod37',to_date('13-MAR-15','DD-MON-RR'),'P_126','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod38',to_date('10-JUL-16','DD-MON-RR'),'P_135','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod39',to_date('02-JUL-13','DD-MON-RR'),'P_35','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod40',to_date('18-OCT-14','DD-MON-RR'),'P_57','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod41',to_date('26-DEC-13','DD-MON-RR'),'P_53','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod42',to_date('30-MAR-13','DD-MON-RR'),'P_12','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod43',to_date('22-JUN-15','DD-MON-RR'),'P_16','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod44',to_date('23-APR-14','DD-MON-RR'),'P_35','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod45',to_date('14-JUL-16','DD-MON-RR'),'P_138','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod46',to_date('29-DEC-16','DD-MON-RR'),'P_97','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod47',to_date('20-OCT-14','DD-MON-RR'),'P_94','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod48',to_date('07-NOV-16','DD-MON-RR'),'P_134','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod49',to_date('26-MAY-14','DD-MON-RR'),'P_157','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod50',to_date('12-JAN-15','DD-MON-RR'),'P_39','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod51',to_date('19-MAR-16','DD-MON-RR'),'P_03','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod52',to_date('15-DEC-13','DD-MON-RR'),'P_114','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod53',to_date('22-JAN-14','DD-MON-RR'),'P_81','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod54',to_date('11-JUL-13','DD-MON-RR'),'P_114','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod55',to_date('24-APR-13','DD-MON-RR'),'P_102','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod56',to_date('05-JUL-14','DD-MON-RR'),'P_152','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod57',to_date('02-JAN-15','DD-MON-RR'),'P_103','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod58',to_date('27-JUL-16','DD-MON-RR'),'P_85','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod59',to_date('14-SEP-13','DD-MON-RR'),'P_75','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod60',to_date('02-SEP-14','DD-MON-RR'),'P_09','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod61',to_date('14-MAY-15','DD-MON-RR'),'P_108','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod62',to_date('30-OCT-13','DD-MON-RR'),'P_160','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod63',to_date('19-FEB-15','DD-MON-RR'),'P_26','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod64',to_date('04-JAN-16','DD-MON-RR'),'P_40','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod65',to_date('10-SEP-16','DD-MON-RR'),'P_96','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod66',to_date('15-APR-13','DD-MON-RR'),'P_167','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod67',to_date('08-JUN-14','DD-MON-RR'),'P_98','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod68',to_date('24-APR-14','DD-MON-RR'),'P_04','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod69',to_date('08-APR-15','DD-MON-RR'),'P_20','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod70',to_date('06-JAN-14','DD-MON-RR'),'P_86','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod71',to_date('27-JAN-13','DD-MON-RR'),'P_91','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod72',to_date('23-SEP-14','DD-MON-RR'),'P_167','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod73',to_date('12-APR-15','DD-MON-RR'),'P_120','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod74',to_date('15-OCT-13','DD-MON-RR'),'P_56','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod75',to_date('11-MAY-15','DD-MON-RR'),'P_156','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod76',to_date('02-SEP-13','DD-MON-RR'),'P_63','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod77',to_date('22-JUL-15','DD-MON-RR'),'P_143','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod78',to_date('12-SEP-13','DD-MON-RR'),'P_13','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod79',to_date('24-JAN-16','DD-MON-RR'),'P_67','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod80',to_date('21-JUL-16','DD-MON-RR'),'P_51','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod81',to_date('14-MAR-14','DD-MON-RR'),'P_160','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod82',to_date('08-DEC-16','DD-MON-RR'),'P_108','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod83',to_date('01-FEB-15','DD-MON-RR'),'P_49','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod84',to_date('12-JUN-13','DD-MON-RR'),'P_103','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod85',to_date('26-FEB-15','DD-MON-RR'),'P_66','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod86',to_date('08-NOV-13','DD-MON-RR'),'P_100','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod87',to_date('11-APR-16','DD-MON-RR'),'P_96','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod88',to_date('15-DEC-14','DD-MON-RR'),'P_94','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod89',to_date('26-FEB-16','DD-MON-RR'),'P_162','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod90',to_date('14-APR-16','DD-MON-RR'),'P_159','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod91',to_date('13-MAY-13','DD-MON-RR'),'P_62','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod92',to_date('27-FEB-16','DD-MON-RR'),'P_87','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod93',to_date('08-NOV-15','DD-MON-RR'),'P_136','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod94',to_date('23-APR-14','DD-MON-RR'),'P_156','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod95',to_date('07-OCT-13','DD-MON-RR'),'P_74','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod96',to_date('15-NOV-14','DD-MON-RR'),'P_131','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod97',to_date('19-APR-15','DD-MON-RR'),'P_107','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod98',to_date('15-JUL-16','DD-MON-RR'),'P_33','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod99',to_date('08-FEB-14','DD-MON-RR'),'P_130','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod100',to_date('28-JUL-14','DD-MON-RR'),'P_23','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod101',to_date('21-AUG-14','DD-MON-RR'),'P_18','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod102',to_date('22-OCT-13','DD-MON-RR'),'P_31','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod103',to_date('28-MAY-13','DD-MON-RR'),'P_124','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod104',to_date('12-OCT-13','DD-MON-RR'),'P_127','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod105',to_date('04-MAR-16','DD-MON-RR'),'P_158','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod106',to_date('03-NOV-15','DD-MON-RR'),'P_90','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod107',to_date('27-FEB-13','DD-MON-RR'),'P_108','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod108',to_date('23-OCT-14','DD-MON-RR'),'P_34','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod109',to_date('06-SEP-13','DD-MON-RR'),'P_02','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod110',to_date('23-MAR-13','DD-MON-RR'),'P_38','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod111',to_date('09-MAY-14','DD-MON-RR'),'P_69','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod112',to_date('24-DEC-13','DD-MON-RR'),'P_42','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod113',to_date('10-NOV-15','DD-MON-RR'),'P_34','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod114',to_date('22-NOV-14','DD-MON-RR'),'P_93','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod115',to_date('10-FEB-15','DD-MON-RR'),'P_136','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod116',to_date('19-SEP-15','DD-MON-RR'),'P_133','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod117',to_date('22-JAN-14','DD-MON-RR'),'P_63','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod118',to_date('17-JUN-14','DD-MON-RR'),'P_101','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod119',to_date('02-MAY-15','DD-MON-RR'),'P_146','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod120',to_date('09-MAY-15','DD-MON-RR'),'P_17','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod121',to_date('03-FEB-15','DD-MON-RR'),'P_134','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod122',to_date('08-SEP-13','DD-MON-RR'),'P_112','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod123',to_date('21-DEC-14','DD-MON-RR'),'P_104','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod124',to_date('16-FEB-14','DD-MON-RR'),'P_127','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod125',to_date('27-SEP-13','DD-MON-RR'),'P_12','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod126',to_date('09-JAN-13','DD-MON-RR'),'P_20','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod127',to_date('12-DEC-15','DD-MON-RR'),'P_91','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod128',to_date('03-JUN-16','DD-MON-RR'),'P_167','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod129',to_date('22-NOV-14','DD-MON-RR'),'P_05','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod130',to_date('24-AUG-16','DD-MON-RR'),'P_08','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod131',to_date('27-JUL-13','DD-MON-RR'),'P_83','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod132',to_date('23-DEC-15','DD-MON-RR'),'P_68','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod133',to_date('23-DEC-14','DD-MON-RR'),'P_85','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod134',to_date('12-OCT-13','DD-MON-RR'),'P_54','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod135',to_date('13-OCT-13','DD-MON-RR'),'P_98','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod136',to_date('19-FEB-14','DD-MON-RR'),'P_06','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod137',to_date('30-SEP-15','DD-MON-RR'),'P_132','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod138',to_date('06-JUN-14','DD-MON-RR'),'P_58','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod139',to_date('20-JUL-13','DD-MON-RR'),'P_90','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod140',to_date('22-OCT-16','DD-MON-RR'),'P_106','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod141',to_date('25-OCT-15','DD-MON-RR'),'P_22','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod142',to_date('12-APR-13','DD-MON-RR'),'P_31','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod143',to_date('29-OCT-13','DD-MON-RR'),'P_21','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod144',to_date('16-DEC-13','DD-MON-RR'),'P_34','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod145',to_date('15-DEC-15','DD-MON-RR'),'P_82','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod146',to_date('22-JUN-15','DD-MON-RR'),'P_105','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod147',to_date('07-APR-16','DD-MON-RR'),'P_19','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod148',to_date('29-APR-14','DD-MON-RR'),'P_24','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod149',to_date('06-JUN-16','DD-MON-RR'),'P_81','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod150',to_date('23-DEC-16','DD-MON-RR'),'P_85','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod151',to_date('22-FEB-16','DD-MON-RR'),'P_64','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod152',to_date('21-JUL-16','DD-MON-RR'),'P_28','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod153',to_date('21-FEB-13','DD-MON-RR'),'P_126','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod154',to_date('20-MAR-13','DD-MON-RR'),'P_156','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod155',to_date('13-JAN-16','DD-MON-RR'),'P_20','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod156',to_date('30-APR-14','DD-MON-RR'),'P_44','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod157',to_date('24-SEP-14','DD-MON-RR'),'P_142','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod158',to_date('04-JAN-13','DD-MON-RR'),'P_96','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod159',to_date('17-SEP-13','DD-MON-RR'),'P_52','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod160',to_date('14-SEP-15','DD-MON-RR'),'P_33','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod161',to_date('23-SEP-16','DD-MON-RR'),'P_130','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod162',to_date('01-JAN-16','DD-MON-RR'),'P_107','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod163',to_date('08-NOV-16','DD-MON-RR'),'P_75','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod164',to_date('17-MAY-16','DD-MON-RR'),'P_13','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod165',to_date('14-OCT-15','DD-MON-RR'),'P_32','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod166',to_date('25-NOV-14','DD-MON-RR'),'P_47','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod167',to_date('27-JAN-15','DD-MON-RR'),'P_141','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod168',to_date('07-SEP-14','DD-MON-RR'),'P_103','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod169',to_date('26-MAR-15','DD-MON-RR'),'P_148','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod170',to_date('09-JUN-15','DD-MON-RR'),'P_90','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod171',to_date('20-APR-16','DD-MON-RR'),'P_62','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod172',to_date('09-DEC-14','DD-MON-RR'),'P_122','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod173',to_date('20-JAN-13','DD-MON-RR'),'P_55','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod174',to_date('07-SEP-14','DD-MON-RR'),'P_73','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod175',to_date('13-FEB-13','DD-MON-RR'),'P_22','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod176',to_date('22-JAN-16','DD-MON-RR'),'P_105','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod177',to_date('28-MAY-14','DD-MON-RR'),'P_105','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod178',to_date('08-MAR-16','DD-MON-RR'),'P_148','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod179',to_date('25-JUL-14','DD-MON-RR'),'P_05','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod180',to_date('06-NOV-15','DD-MON-RR'),'P_67','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod181',to_date('02-JAN-16','DD-MON-RR'),'P_71','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod182',to_date('04-NOV-14','DD-MON-RR'),'P_60','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod183',to_date('15-MAR-13','DD-MON-RR'),'P_12','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod184',to_date('03-MAY-16','DD-MON-RR'),'P_131','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod185',to_date('10-JUL-14','DD-MON-RR'),'P_89','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod186',to_date('01-OCT-13','DD-MON-RR'),'P_103','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod187',to_date('03-MAY-13','DD-MON-RR'),'P_49','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod188',to_date('25-FEB-13','DD-MON-RR'),'P_84','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod189',to_date('03-MAY-15','DD-MON-RR'),'P_50','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod190',to_date('14-SEP-15','DD-MON-RR'),'P_142','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod191',to_date('17-APR-16','DD-MON-RR'),'P_76','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod192',to_date('28-NOV-16','DD-MON-RR'),'P_117','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod193',to_date('30-DEC-14','DD-MON-RR'),'P_70','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod194',to_date('21-NOV-15','DD-MON-RR'),'P_105','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod195',to_date('17-SEP-14','DD-MON-RR'),'P_153','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod196',to_date('22-OCT-15','DD-MON-RR'),'P_21','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod197',to_date('16-JUN-16','DD-MON-RR'),'P_156','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod198',to_date('02-FEB-16','DD-MON-RR'),'P_114','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod199',to_date('13-JUN-15','DD-MON-RR'),'P_159','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod200',to_date('30-MAR-13','DD-MON-RR'),'P_90','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod201',to_date('28-DEC-15','DD-MON-RR'),'P_53','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod202',to_date('27-JUN-13','DD-MON-RR'),'P_161','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod203',to_date('08-FEB-13','DD-MON-RR'),'P_125','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod204',to_date('01-DEC-13','DD-MON-RR'),'P_23','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod205',to_date('13-AUG-15','DD-MON-RR'),'P_19','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod206',to_date('23-FEB-13','DD-MON-RR'),'P_106','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod207',to_date('02-JUN-13','DD-MON-RR'),'P_134','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod208',to_date('07-SEP-14','DD-MON-RR'),'P_148','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod209',to_date('27-JUL-16','DD-MON-RR'),'P_156','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod210',to_date('14-NOV-16','DD-MON-RR'),'P_103','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod211',to_date('03-JAN-16','DD-MON-RR'),'P_156','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod212',to_date('22-OCT-16','DD-MON-RR'),'P_145','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod213',to_date('27-AUG-13','DD-MON-RR'),'P_07','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod214',to_date('03-JAN-14','DD-MON-RR'),'P_149','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod215',to_date('26-DEC-14','DD-MON-RR'),'P_68','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod216',to_date('12-DEC-14','DD-MON-RR'),'P_151','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod217',to_date('07-APR-16','DD-MON-RR'),'P_09','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod218',to_date('09-AUG-16','DD-MON-RR'),'P_128','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod219',to_date('24-JUN-14','DD-MON-RR'),'P_158','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod220',to_date('25-DEC-15','DD-MON-RR'),'P_36','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod221',to_date('05-AUG-15','DD-MON-RR'),'P_155','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod222',to_date('22-JUL-15','DD-MON-RR'),'P_101','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod223',to_date('23-SEP-15','DD-MON-RR'),'P_45','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod224',to_date('09-MAY-14','DD-MON-RR'),'P_67','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod225',to_date('13-MAR-15','DD-MON-RR'),'P_04','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod226',to_date('04-AUG-16','DD-MON-RR'),'P_109','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod227',to_date('01-MAY-15','DD-MON-RR'),'P_125','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod228',to_date('26-MAR-16','DD-MON-RR'),'P_106','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod229',to_date('04-DEC-16','DD-MON-RR'),'P_160','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod230',to_date('04-SEP-15','DD-MON-RR'),'P_19','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod231',to_date('14-JAN-16','DD-MON-RR'),'P_154','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod232',to_date('15-JUL-15','DD-MON-RR'),'P_50','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod233',to_date('08-NOV-16','DD-MON-RR'),'P_26','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod234',to_date('06-OCT-15','DD-MON-RR'),'P_156','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod235',to_date('01-JAN-13','DD-MON-RR'),'P_46','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod236',to_date('24-JUL-15','DD-MON-RR'),'P_118','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod237',to_date('05-OCT-15','DD-MON-RR'),'P_164','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod238',to_date('05-MAY-13','DD-MON-RR'),'P_123','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod239',to_date('01-NOV-16','DD-MON-RR'),'P_70','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod240',to_date('22-NOV-16','DD-MON-RR'),'P_27','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod241',to_date('08-APR-14','DD-MON-RR'),'P_25','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod242',to_date('17-JUN-13','DD-MON-RR'),'P_138','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod243',to_date('28-JAN-15','DD-MON-RR'),'P_76','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod244',to_date('11-FEB-15','DD-MON-RR'),'P_29','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod245',to_date('09-APR-13','DD-MON-RR'),'P_141','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod246',to_date('28-FEB-14','DD-MON-RR'),'P_165','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod247',to_date('07-MAY-16','DD-MON-RR'),'P_22','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod248',to_date('27-MAY-15','DD-MON-RR'),'P_36','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod249',to_date('18-JAN-14','DD-MON-RR'),'P_107','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod250',to_date('04-APR-16','DD-MON-RR'),'P_112','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod251',to_date('23-DEC-15','DD-MON-RR'),'P_163','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod252',to_date('29-JAN-16','DD-MON-RR'),'P_23','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod253',to_date('05-APR-16','DD-MON-RR'),'P_104','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod254',to_date('25-FEB-13','DD-MON-RR'),'P_13','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod255',to_date('11-DEC-15','DD-MON-RR'),'P_75','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod256',to_date('22-DEC-16','DD-MON-RR'),'P_45','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod257',to_date('14-JUN-14','DD-MON-RR'),'P_98','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod258',to_date('20-MAY-15','DD-MON-RR'),'P_162','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod259',to_date('19-MAY-14','DD-MON-RR'),'P_138','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod260',to_date('05-MAY-16','DD-MON-RR'),'P_31','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod261',to_date('05-APR-16','DD-MON-RR'),'P_82','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod262',to_date('06-MAY-14','DD-MON-RR'),'P_13','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod263',to_date('28-SEP-15','DD-MON-RR'),'P_55','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod264',to_date('11-SEP-14','DD-MON-RR'),'P_150','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod265',to_date('18-NOV-16','DD-MON-RR'),'P_126','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod266',to_date('12-JUN-13','DD-MON-RR'),'P_15','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod267',to_date('15-FEB-16','DD-MON-RR'),'P_40','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod268',to_date('10-JAN-15','DD-MON-RR'),'P_163','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod269',to_date('08-AUG-16','DD-MON-RR'),'P_161','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod270',to_date('02-MAR-13','DD-MON-RR'),'P_78','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod271',to_date('21-NOV-16','DD-MON-RR'),'P_41','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod272',to_date('18-JUN-16','DD-MON-RR'),'P_05','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod273',to_date('05-SEP-14','DD-MON-RR'),'P_23','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod274',to_date('14-JAN-16','DD-MON-RR'),'P_138','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod275',to_date('23-APR-13','DD-MON-RR'),'P_54','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod276',to_date('25-MAY-15','DD-MON-RR'),'P_34','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod277',to_date('21-MAY-15','DD-MON-RR'),'P_161','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod278',to_date('25-JUL-13','DD-MON-RR'),'P_141','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod279',to_date('12-MAR-15','DD-MON-RR'),'P_164','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod280',to_date('15-FEB-15','DD-MON-RR'),'P_138','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod281',to_date('16-OCT-15','DD-MON-RR'),'P_100','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod282',to_date('11-JAN-15','DD-MON-RR'),'P_43','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod283',to_date('21-SEP-16','DD-MON-RR'),'P_151','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod284',to_date('23-JUL-16','DD-MON-RR'),'P_138','pro002');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod285',to_date('24-JUL-13','DD-MON-RR'),'P_141','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod286',to_date('10-OCT-14','DD-MON-RR'),'P_163','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod287',to_date('03-JAN-15','DD-MON-RR'),'P_01','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod288',to_date('08-NOV-15','DD-MON-RR'),'P_89','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod289',to_date('07-FEB-15','DD-MON-RR'),'P_40','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod290',to_date('21-DEC-13','DD-MON-RR'),'P_20','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod291',to_date('25-SEP-14','DD-MON-RR'),'P_130','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod292',to_date('25-OCT-14','DD-MON-RR'),'P_31','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod293',to_date('13-OCT-13','DD-MON-RR'),'P_32','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod294',to_date('29-APR-13','DD-MON-RR'),'P_94','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod295',to_date('26-OCT-13','DD-MON-RR'),'P_113','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod296',to_date('05-APR-15','DD-MON-RR'),'P_151','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod297',to_date('17-DEC-13','DD-MON-RR'),'P_07','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod298',to_date('02-APR-15','DD-MON-RR'),'P_87','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod299',to_date('23-JUN-15','DD-MON-RR'),'P_116','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod300',to_date('02-FEB-13','DD-MON-RR'),'P_97','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod301',to_date('06-NOV-14','DD-MON-RR'),'P_156','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod302',to_date('19-MAR-13','DD-MON-RR'),'P_121','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod303',to_date('02-FEB-13','DD-MON-RR'),'P_35','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod304',to_date('17-JAN-14','DD-MON-RR'),'P_07','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod305',to_date('13-MAR-15','DD-MON-RR'),'P_162','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod306',to_date('23-JUN-14','DD-MON-RR'),'P_115','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod307',to_date('24-DEC-16','DD-MON-RR'),'P_111','pro008');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod308',to_date('09-JAN-16','DD-MON-RR'),'P_129','pro007');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod309',to_date('23-NOV-16','DD-MON-RR'),'P_151','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod310',to_date('06-SEP-15','DD-MON-RR'),'P_45','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod311',to_date('28-MAR-13','DD-MON-RR'),'P_151','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod312',to_date('07-AUG-13','DD-MON-RR'),'P_04','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod313',to_date('04-OCT-13','DD-MON-RR'),'P_148','pro010');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod314',to_date('07-OCT-13','DD-MON-RR'),'P_22','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod315',to_date('26-FEB-13','DD-MON-RR'),'P_68','pro004');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod316',to_date('28-DEC-13','DD-MON-RR'),'P_41','pro009');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod317',to_date('19-JUL-15','DD-MON-RR'),'P_116','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod318',to_date('16-JAN-14','DD-MON-RR'),'P_38','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod319',to_date('24-JUL-15','DD-MON-RR'),'P_18','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod320',to_date('30-JUN-16','DD-MON-RR'),'P_44','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod321',to_date('30-APR-13','DD-MON-RR'),'P_165','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod322',to_date('30-SEP-14','DD-MON-RR'),'P_17','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod323',to_date('30-MAY-15','DD-MON-RR'),'P_05','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod324',to_date('30-MAY-16','DD-MON-RR'),'P_123','pro001');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod325',to_date('10-MAR-13','DD-MON-RR'),'P_28','pro003');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod326',to_date('26-MAR-13','DD-MON-RR'),'P_51','pro005');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod327',to_date('03-OCT-14','DD-MON-RR'),'P_102','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod328',to_date('17-DEC-14','DD-MON-RR'),'P_84','pro011');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod329',to_date('18-JAN-15','DD-MON-RR'),'P_120','pro006');
Insert into BIBIM.PROMOTION_DETAIL (PROMD_ID,DATE_SRT,PRODUCT_ID,PROM_ID) values ('prod330',to_date('26-SEP-13','DD-MON-RR'),'P_159','pro002');
--------------------------------------------------------
--  DDL for Index PROMOTION_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIBIM"."PROMOTION_DETAIL_PK" ON "BIBIM"."PROMOTION_DETAIL" ("PROMD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROMOTION_DETAIL
--------------------------------------------------------

  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" MODIFY ("PROMD_ID" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" MODIFY ("DATE_SRT" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" MODIFY ("PROM_ID" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" ADD CONSTRAINT "PROMOTION_DETAIL_PK" PRIMARY KEY ("PROMD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_DETAIL
--------------------------------------------------------

  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" ADD FOREIGN KEY ("PROM_ID")
	  REFERENCES "BIBIM"."PROMOTION" ("PROM_ID") ENABLE;
  ALTER TABLE "BIBIM"."PROMOTION_DETAIL" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "BANK"."PRODUCT" ("PRODUCT_ID") ENABLE;
