--------------------------------------------------------
--  File created - Friday-October-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TYPE_PROMOTION
--------------------------------------------------------

  CREATE TABLE "BIBIM"."TYPE_PROMOTION" 
   (	"TYPEPRO_ID" CHAR(5 BYTE), 
	"TYPEPRO_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BIBIM.TYPE_PROMOTION
SET DEFINE OFF;
Insert into BIBIM.TYPE_PROMOTION (TYPEPRO_ID,TYPEPRO_NAME) values ('tp001','Buy more save more');
Insert into BIBIM.TYPE_PROMOTION (TYPEPRO_ID,TYPEPRO_NAME) values ('tp002','Price off');
--------------------------------------------------------
--  DDL for Index TYPE_PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIBIM"."TYPE_PROMOTION_PK" ON "BIBIM"."TYPE_PROMOTION" ("TYPEPRO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TYPE_PROMOTION
--------------------------------------------------------

  ALTER TABLE "BIBIM"."TYPE_PROMOTION" MODIFY ("TYPEPRO_ID" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."TYPE_PROMOTION" MODIFY ("TYPEPRO_NAME" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."TYPE_PROMOTION" ADD CONSTRAINT "TYPE_PROMOTION_PK" PRIMARY KEY ("TYPEPRO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
