--------------------------------------------------------
--  File created - Friday-October-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TYPE_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "BIBIM"."TYPE_CUSTOMER" 
   (	"TYPECUS_ID" CHAR(5 BYTE), 
	"TYPECUS_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BIBIM.TYPE_CUSTOMER
SET DEFINE OFF;
Insert into BIBIM.TYPE_CUSTOMER (TYPECUS_ID,TYPECUS_NAME) values ('tc001','หน่วยงานราชการ');
Insert into BIBIM.TYPE_CUSTOMER (TYPECUS_ID,TYPECUS_NAME) values ('tc002','บริษัทเอกชน/องค์กร');
Insert into BIBIM.TYPE_CUSTOMER (TYPECUS_ID,TYPECUS_NAME) values ('tc003','ตัวแทนจำหน่าย');
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIBIM"."CUSTOMER_PK" ON "BIBIM"."TYPE_CUSTOMER" ("TYPECUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TYPE_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "BIBIM"."TYPE_CUSTOMER" MODIFY ("TYPECUS_ID" NOT NULL ENABLE);
  ALTER TABLE "BIBIM"."TYPE_CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("TYPECUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BIBIM"."TYPE_CUSTOMER" MODIFY ("TYPECUS_NAME" NOT NULL ENABLE);
